module.exports = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/permissions',
        'getting-started/quick-start',
        'getting-started/sandbox-seed-data',
      ],
    },
    {
      type: 'category',
      label: 'For Administrators',
      items: [
        'admin-guide/configuration',
        'admin-guide/system-settings',
        'admin-guide/how-many-playbooks',
        'admin-guide/playbook-design',
        'admin-guide/scenarios-and-criteria',
        'admin-guide/rules-cookbook',
        'admin-guide/rule-evaluation',
        'admin-guide/pricing-rules',
        'admin-guide/products-and-pricing',
        'admin-guide/view-sections-proposals',
        'admin-guide/approvals',
        'admin-guide/contracts-lifecycle',
        'admin-guide/field-mappings',
        'admin-guide/power-users',
      ],
    },
    {
      type: 'category',
      label: 'For End Users',
      items: [
        'user-guide/workflow-overview',
        'user-guide/creating-quotes',
        'user-guide/managing-quotes',
        'user-guide/quote-line-items',
        'user-guide/submitting-approvals',
        'user-guide/acting-as-approver',
        'user-guide/generating-pdfs',
        'user-guide/contracts-and-amendments',
      ],
    },
    {
      type: 'category',
      label: 'UI Components',
      items: [
        'ui-components/overview',
      ],
    },
    {
      type: 'category',
      label: 'Object Reference',
      items: [
        'objects/overview',
        {
          type: 'category',
          label: 'Admin Objects',
          link: { type: 'doc', id: 'objects/admin/overview' },
          items: [
            'objects/admin/system_settings__c',
            'objects/admin/playbook__c',
            'objects/admin/playbook_scenario__c',
            'objects/admin/playbook_scenario_criterion__c',
            'objects/admin/playbook_question_group__c',
            'objects/admin/playbook_question__c',
            'objects/admin/playbook_rule__c',
            'objects/admin/playbook_rule_action__c',
            'objects/admin/playbook_rule_calculation_item__c',
            'objects/admin/playbook_approval__c',
            'objects/admin/playbook_approver_group__c',
            'objects/admin/playbook_approver__c',
            'objects/admin/playbook_view_section__c',
            'objects/admin/pricing_set__c',
            'objects/admin/pricing_threshold__c',
            'objects/admin/pricebook2',
            'objects/admin/pricebookentry',
            'objects/admin/product2',
            'objects/admin/user',
          ],
        },
        {
          type: 'category',
          label: 'Transaction Objects',
          link: { type: 'doc', id: 'objects/transaction/overview' },
          items: [
            'objects/transaction/quote',
            'objects/transaction/quotelineitem',
            'objects/transaction/playbook_answer__c',
            'objects/transaction/quote_approval__c',
            'objects/transaction/quote_approval_step__c',
            'objects/transaction/quote_approver__c',
            'objects/transaction/quote_proposal__c',
            'objects/transaction/opportunity',
            'objects/transaction/opportunitylineitem',
            'objects/transaction/contract',
            'objects/transaction/contract_entitlement__c',
            'objects/transaction/contract_playbook_answer__c',
            'objects/transaction/contentversion',
          ],
        },
        {
          type: 'category',
          label: 'Custom Metadata Types',
          link: { type: 'doc', id: 'objects/metadata/overview' },
          items: [
            'objects/metadata/opportunity_field_mapping__mdt',
            'objects/metadata/opplineitem_field_mapping__mdt',
            'objects/metadata/entitlement_field_mapping__mdt',
            'objects/metadata/entitlement_combination_mapping__mdt',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'security/data-handling',
        'security/compliance',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        'troubleshooting/common-errors',
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [
        'release-notes/v1-0-0',
      ],
    },
  ],
};
